### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Cretezy** [davidchua/pymessenger#13]
Hey,

Seems like this project doesn't have a license. Do you think we should add one? MIT would be a nice fit for this I'd find.

**Comment by danfairs** [comment]
Hey - yeah, this should definitely have a license. Can't really use it without one. Happy to put together a PR including one, just indicate which one it should be!

**Comment by sils** [comment]
@davidchua this issue is resolved, can you close it?

**Comment by Cretezy** [comment]
Fixed on my fork: https://github.com/Cretezy/pymessenger2
