### ISSUE TITLE
use of enum breaks python2

### ISSUE THREAD

**Issue by tbsf** [davidchua/pymessenger#25]
Python 3 has enum included by default, but Python 2 does not.

To have this work with pip, I suggest we modify the setup.py to the following:

install_requires = [                                                                
    'requests',                                                                     
    'requests-toolbelt',                                                            
    'six'                                                                           
]                                                                                   
                                                                                    
try:                                                                                
    import enum                                                                     
except ImportError:                                                                 
    install_requires.append('enum')

**Comment by tbsf** [comment]
PR https://github.com/davidchua/pymessenger/pull/26

**Comment by Cretezy** [comment]
Fixed #26.
