### ISSUE TITLE
Getting user info and Get Started

### ISSUE THREAD

**Issue by wessilfie** [davidchua/pymessenger#28]
I was digging through the code and noticed a get_user_info method for getting the Facebook info for a given sender, however when I call it, I get an error that it is not part of the bot class.
Examples of how I've tried to call it
`user_info = bot.get_user_info(recipient_id, fields=None)`
`user_info = bot.get_user_info(bot, recipient_id, fields=None)`

Also, does this wrapper yet support having a Get Started and/or persistent menu?

**Comment by Cretezy** [comment]
That's strange, it should work. What's the exact error?
https://developers.facebook.com/docs/messenger-platform/user-profile

However, for the second question, it doesn't need to support it, as that is a single-time operation. You can look at https://developers.facebook.com/docs/messenger-platform/thread-settings for information on setting that up.

**Comment by wessilfie** [comment]
I get this error `AttributeError: 'Bot' object has no attribute 'get_user_info'` with both formats. I'm just trying to collect user_ids so I can send daily messages to users once they've interacted with the bot.

And thanks the the get started link! Just set that up quickly

**Comment by Cretezy** [comment]
Ah, possibly @davidchua didn't release to pip. I'm trying to get him to transfer the project as he's inactive. Try downloading the project manually or getting pip to pull from the GitHub repo.

**Comment by wessilfie** [comment]
yep, thankfully it wasn't too bad to just make my own method to get the result. Hopefully he can transfer the project so more people can work on it. It's a great wrapper!
