### ISSUE TITLE
Code on pip outdated

### ISSUE THREAD

**Issue by 719Ben** [davidchua/pymessenger#29]
The code at https://github.com/davidchua/pymessenger/blob/master/pymessenger/bot.py is currently not the code on pip. Is there anyway to get this updated? Thanks for all the work on this repo!

**Comment by Cretezy** [comment]
https://github.com/davidchua/pymessenger/issues/28

I'm trying to get @davidchua to transfer repo.

**Comment by davidchua** [comment]
Will be pushing a pymessenger release this week. Leaving this open until pip is updated.

**Comment by sils** [comment]
Any news?

**Comment by Cretezy** [comment]
Fixed on my fork: https://github.com/Cretezy/pymessenger2

**Comment by 719Ben** [comment]
I don't know if I would call this fixed. @davidchua can you please comment?
