### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by sils** [davidchua/pymessenger#33]
I think this is an interesting project but a lot of PRs and issues don't seem to get the attention they need which usually leads to contriutor frustration, I'd be willing to contribute but not if things won't get merged eventually.

@davidchua are you the only maintainer? @Cretezy seems to be quite active too.
Why are the builds failing on master and nobody seems to care?
And finally is it worth my time to contribute or should I fork it? I could possibly help maintaining things related to features I need but I can't make promises at this stage.

**Comment by Cretezy** [comment]
I'm going to be forking this project soon. Stay updated

**Comment by Cretezy** [comment]
https://github.com/Cretezy/pymessenger2/
