### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by Jzarecta** [davidchua/pymessenger#4]
is this module available for python3?

Also tried import Bot but got issues:
```
>> from pymessenger import Bot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Bot
```

**Comment by Jzarecta** [comment]
fixed it but it seems the class is bot and not **Bot**

**Comment by davidchua** [comment]
Hi @Jzarecta,

Thanks for bringing attention to this! README has been updated:

Reference: https://github.com/davidchua/pymessenger/pull/3
