### ISSUE TITLE
Element Python3 

### ISSUE THREAD

**Issue by jmortley** [davidchua/pymessenger#9]
Just a heads up had to edit the Element class to work for my bot as iteritems does not exist in python3.
I'm sure in the init you can add a case for Python3 to use **.items()** .

For my use case I just skipped importing Element and defined it in my Django View. 
class Element(dict):
    __acceptable_keys = ['title', 'item_url', 'image_url', 'subtitle', 'buttons']
    def __init__(self, *args, **kwargs):
        kwargs = {k:v for k, v in kwargs.items() if k in self.__acceptable_keys}
        super(Element, self).__init__(*args, **kwargs)

**Comment by tbsf** [comment]
Thanks for the heads up! There is another issue with python3 if you use appsecret_proof. I will try to take a look sometime but feel free to open a PR if you know a fix that works with both versions.

**Comment by tbsf** [comment]
@jmortley This has been fixed in release 0.0.6
